In [1]:
import numpy as np
import scipy

In [2]:
from scipy.io import loadmat

In [3]:
from sklearn.multiclass import OneVsRestClassifier
from sklearn.svm import SVC

In [4]:
X = np.array(loadmat('digit_dataSet.mat')['X'])
y = np.array(loadmat('digit_dataSet.mat')['y'])

In [5]:
X.shape

(5000, 400)

In [6]:
y.shape

(5000, 1)

In [7]:
X[np.random.randint(X.shape[0], size=10), :]

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [8]:
y[np.random.randint(y.shape[0], size=10), :]

array([[9],
       [1],
       [6],
       [8],
       [9],
       [2],
       [5],
       [3],
       [5],
       [9]], dtype=uint8)

In [9]:
data = np.concatenate((X,y), axis=1)

In [10]:
data.shape

(5000, 401)

In [11]:
data = data[np.random.randint(data.shape[0], size=5000), :]

In [12]:
x_train = data[0:3000,0:400]

In [13]:
y_train = data[0:3000,400:401]

In [14]:
x_train.shape

(3000, 400)

In [15]:
y_train.shape

(3000, 1)

In [16]:
x_test = data[3000:5001,0:400]

In [17]:
y_test = data[3000:5001,400:401]

In [18]:
x_test.shape

(2000, 400)

In [19]:
y_test.shape

(2000, 1)

In [20]:
clf = OneVsRestClassifier(SVC()).fit(x_train, y_train)

In [21]:
clf.predict(x_test[0:3,:])

array([ 1.,  4., 10.])

In [22]:
y_test[0:3,:]

array([[ 1.],
       [ 4.],
       [10.]])

In [23]:
type(clf)

sklearn.multiclass.OneVsRestClassifier

In [24]:
x_test[:,0:1]

array([[0.],
       [0.],
       [0.],
       ...,
       [0.],
       [0.],
       [0.]])

In [25]:
import pandas as pd

In [26]:
data = np.genfromtxt("dataset.csv", delimiter=',')

In [27]:
import cv2

In [28]:
images = data[:,1:785]

In [29]:
images.shape

(85, 784)

In [30]:
for i in range(20):
    img = images[i]
    cv2.imshow("image", img.reshape(28,28))
    cv2.waitKey()
    cv2.destroyAllWindows()

In [32]:
clf.score(x_test,y_test)

0.967